# Font
font_family Menlo
font_size 14
disable_ligatures cursor 
# General
term xterm-256color
open_url_modifiers ctrl
scrollback_lines 2500
enable_audio_bell no
window_padding_width 0
clipboard_control write-clipboard write-primary
#cursor_stop_blinking_after 1.0
background_opacity 0.95
background_blur 64

# Hide window title bar
hide_window_decorations yes

######
# Keys
######
macos_option_as_alt left
map cmd+enter launch --location=hsplit --cwd=current
map cmd+shift+enter launch --location=vsplit --cwd=current
# map ctrl+tab next_tab
# map ctrl+shift+tab previous_tab


# BEGIN_KITTY_THEME
# Rosé Pine Moon
include current-theme.conf
# END_KITTY_THEME
